services:

  # !!! Containers in this file are meant to be started via `scripts/run-tests.ts`, not manually.
  # For example, `links:` are not defined below and it's up to the script to start the containers properly.
  # PR #1401 explains why.

  wordpress-for-tests:
    image: versionpress/wordpress:php8.2-apache
    ports:
      - "80:80"
    volumes:
      - wordpress-files:/var/www/html:z
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /var/www/html/wptest
    environment:
      WORDPRESS_DB_HOST: mysql-for-tests
      WORDPRESS_DB_PASSWORD: r00tpwd

  mysql-for-tests:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data-for-tests:/var/lib/mysql:z
    environment:
      MYSQL_ROOT_PASSWORD: r00tpwd
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password

  tests-with-wordpress:
    image: versionpress/wordpress:cli
    environment:
      VP_DIR: /opt/versionpress
      PHP_IDE_CONFIG: serverName=VersionPress-tests
      XDEBUG_SESSION: 1
    user: "33"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # !!! This must be kept in sync with wordpress-cli-image/Dockerfile
      - wordpress-files:/var/www/html:z
      - test-logs:/var/opt/versionpress/logs:z
      - ./plugins/versionpress:/opt/versionpress:z
      - ./ext-libs:/opt/ext-libs:ro,z
      - wpcli-cache:/var/www/.wp-cli:z
    working_dir: /opt/versionpress/tests
    command: ../vendor/bin/phpunit --verbose --colors -c phpunit.xml --testdox-text /var/opt/versionpress/logs/testdox.txt

  tests:
    image: versionpress/wordpress:cli
    environment:
      VP_DIR: /opt/versionpress
      PHP_IDE_CONFIG: serverName=VersionPress-tests
      XDEBUG_SESSION: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # !!! This must be kept in sync with wordpress-cli-image/Dockerfile
      - wordpress-files:/var/www/html:z
      - test-logs:/var/opt/versionpress/logs:z
      - ./plugins/versionpress:/opt/versionpress:ro,z
      - ./ext-libs:/opt/ext-libs:ro,z
      - wpcli-cache:/var/www/.wp-cli:z
    working_dir: /opt/versionpress/tests
    command: ../vendor/bin/phpunit --verbose --colors -c phpunit.xml --testdox-text /var/opt/versionpress/logs/testdox.txt

  wait:
    image: janvoracek/docker-wait@sha256:2d91ec68cf3e0dbcd03addaded0af238944f75378f5062358bd3c5fb839b60d2
    environment:
      - TIMEOUT=120
      # - TARGETS are specified in run-tests.ts

  selenium-hub:
    # Standalone Firefox is enough but could also be a full grid setup, hence the service name
    image: selenium/standalone-firefox@sha256:541e4d726136b3fbf0220c1feb4d3a76c577d302e77050f1191a0d5b3a029c10

  copy-files-to-host:
    image: alpine@sha256:644fcb1a676b5165371437feaa922943aaf7afcfa8bfee4472f6860aad1ef2a0
    volumes:
      - wordpress-files:/tmp/wp
      - ./dev-env/wp-for-tests:/tmp/wp-copy
      - test-logs:/tmp/test-logs
      - ./dev-env/test-logs:/tmp/test-logs-copy
    command: '/bin/sh -c "cp -a /tmp/test-logs/. /tmp/test-logs-copy/; cp -a /tmp/wp/. /tmp/wp-copy/"'

volumes:
  db-data-for-tests:
  wpcli-cache:
  wordpress-files:
  test-logs:
